import type { Metadata } from 'next';
import { PageHeader } from '@/components/page-header';
import { REPO_URL } from '@/lib/knowledge';

export const metadata: Metadata = { title: 'Contributing', description: 'Add or revise source-backed openPrompting knowledge entries and task templates.', alternates: { canonical: '/contributing' } };

export default function ContributingPage() {
  return <><PageHeader title="Contributing" lede="Most contributions add or revise knowledge entries. The CLI router does not need to change for a new model, harness, or task to appear." /><section className="section"><div className="wrap"><div className="two-col"><div><div className="eyebrow">Where to work</div><ul className="prose-list mt-3"><li><code className="mono">knowledge/models/</code> — model entries</li><li><code className="mono">knowledge/harnesses/</code> — harness entries</li><li><code className="mono">knowledge/tasks/</code> — task entries</li><li><code className="mono">templates/</code> — task prompt templates (one per task, same id)</li></ul><p className="small dim mt-4">Use a globally unique lowercase kebab-case <span className="mono">id</span>, classify every claim as <span className="mono">official</span>, <span className="mono">tested</span>, <span className="mono">community</span>, or <span className="mono">legacy</span>, and record <span className="mono">last_verified</span> dates. Then run <span className="mono">pnpm validate:knowledge</span> and the release gates.</p></div><div className="panel"><h3>Core principle</h3><p className="dim small">Existence alone is not enough reason for an entry. A model or harness should have useful, maintainable, sourceable guidance. If a claim cannot be sourced, classify it honestly — including as <em>community</em>. Never present preference or an unscoped ranking as fact.</p></div></div><section className="block"><h2>What a good entry includes</h2><ul className="prose-list"><li>A short, factual summary that does not rank or promote.</li><li>Recommended practices grounded in documented or tested behavior.</li><li>Cautions that name specific failure modes.</li><li>Structured evidence entries with a class, a source, and verification dates.</li><li>Model behavior kept in model entries; harness behavior (instruction files, permissions) in harness entries.</li><li>No invented numbers, benchmarks, or adoption claims.</li></ul></section><div className="mt-8 cta-row"><a className="btn" href={`${REPO_URL}/blob/main/CONTRIBUTING.md`} rel="noreferrer">Read CONTRIBUTING.md ↗</a><a className="btn btn--ghost" href={REPO_URL} rel="noreferrer">Open repository ↗</a></div></div></section></>;
}
