import Link from 'next/link';
import type { Catalog } from '@/lib/content-types';
import { NPM_INSTALL, REPO_URL } from '@/lib/knowledge';
import { bulletsOf, splitSections } from '@/lib/markdown';
import { CodeBlock, EvidenceCards, SelectionPreview } from './knowledge-content';
import { GuidanceExplorer, type ExplorerEntry } from './guidance-explorer';

function explorerEntry(entry: Catalog['models'][number]): ExplorerEntry;
function explorerEntry(entry: Catalog['harnesses'][number]): ExplorerEntry;
function explorerEntry(entry: Catalog['tasks'][number]): ExplorerEntry;
function explorerEntry(entry: Catalog['models'][number] | Catalog['harnesses'][number] | Catalog['tasks'][number]): ExplorerEntry {
  return { id: entry.id, displayName: entry.displayName, recommended: bulletsOf(splitSections(entry.body), 'Recommended').slice(0, 3) };
}

function explorerPresets(catalog: Catalog) {
  const find = (kind: keyof Pick<Catalog, 'models' | 'harnesses' | 'tasks'>, id: string) => catalog[kind].find((entry) => entry.id === id);
  const candidateSets = [
    ['openai-gpt-6-astra', 'codex', 'planning', 'Astra · Codex · Planning'],
    ['anthropic-claude-sonnet-5', 'claude-code', 'review', 'Sonnet 5 · Claude Code · Review'],
    ['google-gemini-3-8-flash', 'gemini-cli', 'research', 'Gemini 3.8 Flash · Gemini CLI · Research'],
  ] as const;
  return candidateSets.flatMap(([model, harness, task, label]) => find('models', model) && find('harnesses', harness) && find('tasks', task) ? [{ model, harness, task, label }] : []);
}

function defaultSelection(catalog: Catalog) {
  const preset = explorerPresets(catalog)[0];
  return preset ? { model: preset.model, harness: preset.harness, task: preset.task } : { model: catalog.models[0].id, harness: catalog.harnesses[0].id, task: catalog.tasks[0].id };
}

function Hero({ catalog }: { catalog: Catalog }) {
  return <section className="hero"><div className="wrap"><div className="hero__grid"><div><div className="eyebrow">OPEN SOURCE · LOCAL-FIRST · SOURCE-BACKED</div><h1><span className="hero__headline-line">Build prompts that <em>fit</em></span>{' '}<span className="hero__headline-line">the way you actually work.</span></h1><p className="hero__lede">openPrompting combines model-specific prompting guidance, coding-tool context and behavior, and task-specific structure into a prompt that fits your setup.</p><p className="hero__lede hero__lede--secondary">Choose the AI model you’re using, the tool you’re working in, and what you’re trying to do. openPrompting brings the relevant guidance together — without calling another AI.</p><p className="hero__trust mono">No API key · No model calls · No backend</p><div className="hero__cta"><Link className="btn" href="#explore">See how it works</Link><Link className="btn btn--ghost" href="/models">Browse guidance</Link><a className="btn btn--ghost" href={REPO_URL} rel="noreferrer">GitHub ↗</a></div></div><aside className="hero__aside" aria-label="Install"><div className="eyebrow">Install</div><div className="mt-3"><CodeBlock command={NPM_INSTALL} large /></div><ul className="hero__facts"><li><span className="k">Release</span><span>v{catalog.version} · 1.1.x line</span></li><li><span className="k">Runtime</span><span>Node.js 20+, no network after install</span></li><li><span className="k">Catalog</span><span>{catalog.models.length} models · {catalog.harnesses.length} harnesses · {catalog.tasks.length} tasks</span></li></ul></aside></div></div></section>;
}

export function HomePage({ catalog }: { catalog: Catalog }) {
  const presets = explorerPresets(catalog);
  const selection = defaultSelection(catalog);
  const cursor = catalog.harnesses.find((entry) => entry.id === 'cursor') ?? catalog.harnesses[0];
  return <>
    <Hero catalog={catalog} />
    <section className="section" id="explore" aria-labelledby="explore-h"><div className="wrap"><div className="eyebrow">§ 01 — HOW IT WORKS</div><h2 className="mt-2" id="explore-h">One prompt doesn’t fit every setup.</h2><p className="lede mt-3">Different AI models respond differently to instructions. Coding tools manage context and project rules in different ways. And planning a feature needs a different structure from fixing a bug.</p><p className="lede mt-3">openPrompting combines all three into guidance for the setup you’re actually using.</p><GuidanceExplorer models={catalog.models.map(explorerEntry)} harnesses={catalog.harnesses.map(explorerEntry)} tasks={catalog.tasks.map(explorerEntry)} presets={presets} defaultSelection={selection} /><ul className="meta mt-6" aria-label="Technical terms"><li><span className="k">Model</span><span className="v">How this AI responds best to instructions.</span></li><li><span className="k">Harness</span><span className="v">How your coding tool handles context and project instructions.</span></li><li><span className="k">Task</span><span className="v">What structure this kind of work needs.</span></li></ul><p className="small dim mt-4" style={{ maxWidth: '66ch' }}>Selections above are choices, not rankings. openPrompting does not rank models or imply that any combination is objectively superior. Profiles are user-defined.</p></div></section>
    <section className="section"><div className="wrap"><div className="eyebrow">§ 02 — Catalog</div><h2 className="mt-2">A browsable index of the current knowledge base.</h2><p className="lede mt-3">Every entry is a versioned document in the repository with structured evidence and a verification date. New entries appear here automatically at build time.</p><div className="catalog-grid"><Link className="catalog-cell" href="/models"><div className="catalog-cell__n">{catalog.models.length}<small>Models</small></div><p>Provider models with prompting guidance scoped to model behavior.</p><span className="catalog-cell__go">Browse models →</span></Link><Link className="catalog-cell" href="/harnesses"><div className="catalog-cell__n">{catalog.harnesses.length}<small>Harnesses</small></div><p>Coding-agent tools with instruction-file, context, and permission guidance.</p><span className="catalog-cell__go">Browse harnesses →</span></Link><Link className="catalog-cell" href="/tasks"><div className="catalog-cell__n">{catalog.tasks.length}<small>Tasks</small></div><p>Reusable work patterns with cautions and prompt skeletons.</p><span className="catalog-cell__go">Browse tasks →</span></Link></div></div></section>
    <section className="section"><div className="wrap"><div className="eyebrow">§ 03 — Real entry</div><h2 className="mt-2">What a knowledge entry actually contains.</h2><p className="lede mt-3">Pulled directly from <code className="mono">{cursor.entryPath}</code> at build time — not written for this page.</p><SelectionPreview entry={cursor} /></div></section>
    <section className="band"><div className="wrap"><div className="eyebrow">§ 04 — Local-first</div><h2>Normal operation touches nothing outside your machine.</h2><p>openPrompting resolves guidance from a local knowledge base. After installation it needs no account, no API key, no model call, no hosted backend, and no network connection. <span className="band__note">Setup is the only command that writes project state; doctor is read-only.</span></p><ul className="no-list">{['No account', 'No API key', 'No model call', 'No hosted backend', 'No telemetry', 'No runtime network'].map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <section className="section" id="evidence"><div className="wrap"><div className="eyebrow">§ 05 — Evidence</div><h2 className="mt-2">Every claim has a source and a class.</h2><p className="lede mt-3">Each knowledge entry carries structured evidence metadata: what class of evidence supports a claim, which source it came from, and when that source was last checked. Every entry page surfaces that metadata.</p><EvidenceCards /><div className="mt-8"><Link className="btn btn--ghost" href="/docs#evidence">Read the evidence model →</Link></div></div></section>
    <section className="section"><div className="wrap"><div className="eyebrow">§ 06 — CLI</div><h2 className="mt-2">Six commands. Nothing hidden.</h2><p className="lede mt-3">The command line configures, resolves, generates, diagnoses, and compares. It never calls a model — it reads the same knowledge you are browsing here.</p><div className="cli">{['help', 'setup', 'guide', 'new', 'doctor', 'compare'].map((command) => { const descriptions: Record<string, string> = { help: 'Show the command list and common examples. No config required.', setup: 'Create or update .openprompting/config.yml; --check validates without writing.', guide: 'Display resolved model and harness guidance: recommendations, cautions, evidence, sources.', new: 'Render a deterministic prompt skeleton for a task. No model call, no invented facts.', doctor: 'Run read-only local diagnostics. Never executes project scripts.', compare: 'Compare two profiles, setups, models, or harnesses from documented evidence. No winner inferred.' }; const examples: Record<string, string> = { help: 'openprompting help', setup: 'openprompting setup', guide: 'openprompting guide --profile reviewer', new: 'openprompting new planning', doctor: 'openprompting doctor', compare: 'openprompting compare builder reviewer' }; return <div className="cli__row" key={command}><code className="cli__cmd">{command}</code><div className="cli__desc">{descriptions[command]}<span className="cli__ex mono">{examples[command]}</span></div></div>; })}</div><p className="small dim mt-4">Full selectors, resolution rules, and exit behavior: <Link href="/docs#commands">Docs →</Link></p></div></section>
    <section className="section"><div className="wrap"><div className="eyebrow">§ 07 — Start</div><h2 className="mt-2">From install to a real task prompt in four steps.</h2><ol className="steps">{[['Install', NPM_INSTALL], ['Configure', 'openprompting setup'], ['Read guidance', 'openprompting guide'], ['Start a task', 'openprompting new planning']].map(([title, command], index) => <li className="step" key={title}><div className="step__n">{String(index + 1).padStart(2, '0')}</div><div><div className="step__t">{title}</div></div><div className="step__code"><CodeBlock command={command} /></div></li>)}</ol><div className="mt-6"><Link className="btn" href="/start">Full getting started →</Link></div></div></section>
    <section className="section"><div className="wrap newcomer"><div className="eyebrow">§ 08 — New here</div><h2 className="mt-2">Agentic coding, in one paragraph.</h2><p className="lede mt-3">A <strong>model</strong> reasons and generates; a <strong>harness</strong> gives it repository access, tools, and instruction files. Together they form a <strong>setup</strong>, which you can name as a <strong>profile</strong>. Good prompting is rarely magic words — it is giving the agent goals, context, requirements, constraints, acceptance criteria, and validation.</p><div className="mt-6"><Link className="btn btn--ghost" href="/docs">Learn the vocabulary →</Link></div></div></section>
  </>;
}
